### ISSUE TITLE
Meta-issue: Features to add

### ISSUE THREAD

**Issue by abingham** [sixty-north/python-camtasia#6]
# Media Bin
- [ ] Rename media-bin media
- [ ] Support importing audio media

# Timeline
- [ ] Adding and removing timeline markers

# Tracks
- [ ] edit name
- [ ] change index / move track (not supported in camtasia, but feasible)
- [ ] toggle audio-muted
- [ ] toggle video hidden

# Track media
- [ ] Add/remove/edit markers
- [ ] Change start and duration
- [ ] Edit media-start (i.e. offset into underlying bin-media)

# Annotation
- [ ] Add/remove/edit annotations

**Comment by Phildrummer** [comment]
Hi,
I noticed that the annotations class is not working in the camtasia 6.3.0 version.
I saw that the __init__.py is empty. Is this a mistake?

**Comment by abingham** [comment]
Could you open a new issue with details about what's not working? The file `annotations/__init__.py` is intentionally empty.
